### ISSUE TITLE
ImportError: No module named request

### ISSUE THREAD

**Issue by xmattstrongx** [jxmorris12/PokemonGo-Finder#13]
Unable to run main program :(
### Environment info

Operating System: MACOS

Installed version of Python: 2.7
### Steps to reproduce
1. Download repo
2. Follow all instructions (pip install, pushbullet etc)
3. python main.py
### What have you tried?
1. python main.py
### Logs or other output that would be helpful

(If logs are large, please upload as attachment).

``````
Traceback (most recent call last):
  File "main.py", line 4, in <module>
    import flask
  File "/usr/local/lib/python2.7/site-packages/flask/__init__.py", line 17, in <module>
    from werkzeug.exceptions import abort
  File "/usr/local/lib/python2.7/site-packages/werkzeug/__init__.py", line 152, in <module>
    __import__('werkzeug.exceptions')
  File "/usr/local/lib/python2.7/site-packages/werkzeug/exceptions.py", line 71, in <module>
    from werkzeug.wrappers import Response
  File "/usr/local/lib/python2.7/site-packages/werkzeug/wrappers.py", line 26, in <module>
    from werkzeug.http import HTTP_STATUS_CODES, \
  File "/usr/local/lib/python2.7/site-packages/werkzeug/http.py", line 28, in <module>
    from urllib.request import parse_http_list as _parse_list_header
ImportError: No module named request```
``````

**Comment by xmattstrongx** [comment]
Solved

```
pip install virtualenv
virtualenv venv
source venv/bin/activate
pip install -r requirements.txt
```

**Comment by jxmorris12** [comment]
awesome. congrats on fixing it dude
