### ISSUE TITLE
Unexpected Error. Can't run Main.py.

### ISSUE THREAD

**Issue by Silvawar14** [jxmorris12/PokemonGo-Finder#41]
## Expected Behavior

Double click Main.py or run it in cmd.
## Current Behavior

An error occurs. Here's the Traceback. (I'm not knowledgeable enough to decipher.)

```
Traceback (most recent call last):
  File "main.py", line 5, in <module>
    import notifier
  File "C:\Pokemon Go\PokemonGo-Finder-master 7-22\PokemonGo-Finder-master Eagles Landing\notifier.py", line 68, in <module>
    init()
  File "C:\Pokemon Go\PokemonGo-Finder-master 7-22\PokemonGo-Finder-master Eagles Landing\notifier.py", line 35, in init
    pushbullet_client = Pushbullet(api_key)
  File "C:\Python27\lib\site-packages\pushbullet\pushbullet.py", line 29, in __init__
    self.refresh()
  File "C:\Python27\lib\site-packages\pushbullet\pushbullet.py", line 290, in refresh
    self._load_user_info()
  File "C:\Python27\lib\site-packages\pushbullet\pushbullet.py", line 62, in _load_user_info
    self.user_info = self._get_data(self.ME_URL)
  File "C:\Python27\lib\site-packages\pushbullet\pushbullet.py", line 32, in _get_data
    resp = self._session.get(url)
  File "C:\Python27\lib\site-packages\requests\sessions.py", line 487, in get
    return self.request('GET', url, **kwargs)
  File "C:\Python27\lib\site-packages\requests\sessions.py", line 475, in request
    resp = self.send(prep, **send_kwargs)
  File "C:\Python27\lib\site-packages\requests\sessions.py", line 585, in send
    r = adapter.send(request, **kwargs)
  File "C:\Python27\lib\site-packages\requests\adapters.py", line 453, in send
    raise ConnectionError(err, request=request)
requests.exceptions.ConnectionError: ('Connection aborted.', BadStatusLine("''",))
```
## Possible Solution

None provided.
## Steps to Reproduce (for bugs)

1. Run Main.py
## Your Environment

- Version used: Most recent plus a couple pulls to make the notification work.
- Environment name and version (e.g. Python 2.7): Python 2.7
- Operating System and version (desktop or mobile): Windows 10.0.10586

It's important to note that this script was working perfectly 10 hours ago and for the last two days. What changed? Something temporary or something permanent?

**Comment by paperc07** [comment]
lol wow yeah I am getting this error now too

**Comment by Silvawar14** [comment]
It looks like PTC is having some stability issues.

I wonder if that's the issue.

**Comment by paperc07** [comment]
No I am using Google not ptc

**Comment by paperc07** [comment]
Ok I found my issue, I had a GPS coordinate and it had symbols in it and not just numbers anywyas I regot the GPS cords and it's working now
